language: c

env:
  - SQC_NONZERO_EXIT=1

before_install:
  - sudo apt-get install python3

script:
  - autoconf
  - ./configure
  - make
  - make dev
  - miniapps/esl-shuffle.itest.py . . foo
  - make check

